### ISSUE TITLE
Feature request: attach a livereload server to broccoli serve

### ISSUE THREAD

**Issue by jamesarosen** [stfsy/broccoli-inject-livereload#3]
This would require some coordination with @joliss, but it would be awesome if this plugin could also add a [tiny-lr](https://www.npmjs.com/package/tiny-lr) server to `broccoli serve` to complete the chain. That way, users wouldn't have to install the LiveReload app separately.

**Comment by andre-meier** [comment]
I was also thinking about such feature, as it would get "non-ember" users a "ember-cli" like experience when using broccoli as a build system. I even started implementing it but threw it away for different reasons and am now using a combination of grunt + grunt-broccoli (my fork, since the original repo is no longer maintained) + grunt-contrib-livereload.

Maybe this would also be a way to go for you?

**Comment by stfsy** [comment]
@jamesarosen @andre-meier meanwhile i implemented a broccoli plugin that starts a livereload server **and** injects the livereload script into html files: https://github.com/stfsy/broccoli-livereload.

will merge both plugins in the coming weeks as they'll share a lot of code after i merged the current dev branch
